### ISSUE TITLE
Is it possible to set the value in range and request a value?

### ISSUE THREAD

**Issue by blynkkk** [ilcato/homebridge-ifttt#5]
Awesome plugin! Great job, really.

Could you please provide an example of how the JSON configuration would look for this cases?
Example: 
- Siri, what's the humidity level?
- Humidity is 38%  

------
- Siri, set the bedroom lights to 50%
- Done

Thank you, @ilcato

**Comment by ilcato** [comment]
@blynkkk: with this plugin you are only able to activate a trigger on an IFTTT Maker Channel.

It is possible to develop a mapping to for example an HomeKit accessory of type Lightbulb in order to communicate to the Channel also a value. The problem is querying the Channel for a current value.

So: currently your two scenarios are not possible with this plugin.

Do you have same specific recipes in mind? Can you elaborate?

**Comment by blynkkk** [comment]
We at [Blynk](http://blynk.cc) just thinking about the easiest way to connect Siri to the app, so were exploring different options. 

My thinking was having not only a trigger, but also a query, that will return value. For example, if I have a humidity sensor, connected to my Arduino, I could create a recipe to ask Siri about the humidity level.

I think that this indeed is out of scope for your wonderful plugin. Anyway, thanks for a great job!

**Comment by ilcato** [comment]
I understand.
I think that the best way to integrate Siri with Blynk (I'm testing it from some time now) is to develop an homebridge plugin for the Blynk Server. 
I will create a PoC it in the next few days.

**Comment by ilcato** [comment]
@blynkkk : have a look at [https://www.npmjs.com/package/homebridge-blynk](url)
It currently manage pins through an HomeKit switch.

**Comment by blynkkk** [comment]
Thanks for moving with it!
